name: CI/CD Pipeline (Feature Branch)

# Only trigger on pushes to feature/ci-cd branch
on:
  push:
    branches: [ "feature/ci-cd" ]
  # Optional: Add pull_request trigger if needed
  # pull_request:
  #   branches: [ "feature/ci-cd" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm test

  build-docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            your-dockerhub-username/node-app:feature-ci-cd
            your-dockerhub-username/node-app:${{ github.sha }}

  deploy-preview:
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploying to preview environment"
      # Replace with your actual deployment command
      - run: curl -X POST "https://api.render.com/deploy?key=${{ secrets.RENDER_KEY }}&branch=feature/ci-cd"
